spring.application.name=Edifika-Microservice-Payment

# Servidor
server.port=${PORT:8084}

# DB Local PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0}
spring.datasource.username=${DATABASE_USERNAME:postgres.vqxuzgneldhiwkibsfbk}
spring.datasource.password=${DATABASE_PASSWORD:1Fwa8hkub4uwdjBh}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=com.edifika.payment.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false

# JWT mismo secret que IAM
jwt.secret=${JWT_SECRET:edifika-secret-key-must-be-at-least-32-characters-long}
jwt.expiration.days=${JWT_EXPIRATION_DAYS:365}

# Documentacion
documentation.application.description=@project.description@
documentation.application.version=@project.version@